branch-defaults:
  default:
    environment: Demo999-env
    group_suffix: null
deploy:
  artifact: dist/dist.zip
global:
  application_name: demo999
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
