version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
executors:
  base-executor:
    docker:
      - image: cimg/node:17.3.0
    working_directory: /temp
jobs:
  Install:
    executor: base-executor
    steps:
      - checkout
      - aws-cli/setup
      - eb/setup
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "server/package.json" }}
      - run:
          name: Install BackEnd Dependencies
          command: |
            npm run install:server
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "server/package.json" }}
          paths: 
            - server/node_modules  
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "client/package.json" }}
      - run:
          name: Install FrontEnd Dependencies
          command: |
            npm run install:client
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "client/package.json" }}
          paths: 
            - client/node_modules  
      - run:
          name: Lint FrontEnd Application
          command: |
            npm run lint:client
      - run:
          name: Lint Backend Application
          command: |
            npm run lint:server
workflows:
  Storefront:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - master
