version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
executors:
  base-executor:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - aws-cli/setup
jobs:
  Install:
    executor: base-executor
    steps:
      - run:
          name: Install FrontEnd Dependencies
          command: |
            npm run install:client
      - run:
          name: Install BackEnd Dependencies
          command: |
            npm run install:server
  Lint:
    executor: base-executor
    steps:
      - run:
          name: Lint FrontEnd Application
          command: |
            npm run lint:client
      - run:
          name: Lint Backend Application
          command: |
            npm run lint:server
  Test:
    executor: base-executor
    steps:
      - run:
          name: Test FrontEnd Application
          command: |
            npm run test:client
  Build:
    executor: base-executor
    steps:
      - run:
          name: Build BackEnd
          command: |
            npm run build:server
      - run:
          name: Build FrontEnd
          command: |
            npm run build:client
  Deploy:
    executor: base-executor
    steps:
      - run:
          name: Deploy FrontEnd App
          command: |
            npm run deploy

workflows:
  Storefront:
    jobs:
      - Install
      - Lint:
          requires:
            - Install
      - Test:
          requires:
            - Install
            - Lint
      - Build:
          requires:
            - Install
            - Lint
            - Test
          filters:
            branches:
              only:
                - main
                - master
      - Deploy:
          requires:
            - Install
            - Lint
            - Test
            - Build
          filters:
            branches:
              only:
                - main
                - master
