version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Install FrontEnd Dependencies
          command: |
            npm run install:client
      - run:
          name: Install BackEnd Dependencies
          command: |
            npm run install:server
      - run:
          name: Lint FrontEnd Application
          command: |
            npm run lint:client
      - run:
          name: Lint Backend Application
          command: |
            npm run lint:server
      - run:
          name: Test FrontEnd Application
          command: |
            npm run test:client
      - run:
          name: Build BackEnd
          command: |
            npm run build:server
          filters:
            branches:
              only:
                - main
      - run:
          name: Build FrontEnd
          command: |
            npm run build:client
          filters:
            branches:
              only:
                - main
      - run:
          name: Deploy FrontEnd App
          command: |
            npm run deploy
          filters:
            branches:
              only:
                - main
