version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install BackEnd Dependencies
          command: |
            npm run install:server
      - run:
          name: Install FrontEnd Dependencies
          command: |
            npm run install:client
      - run:
          name: Test FrontEnd Application
          command: |
            npm run test:client
      - run:
          name: Build BackEnd
          command: |
            npm run build:server
      - run:
          name: Build FrontEnd
          command: |
            npm run build:client
      - run:
          name: Deploy Backend App
          command: |
            npm run deploy:server
      - run:
          name: Deploy FrontEnd App
          command: |
            npm run deploy:client
workflows:
  Storefront:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - master