version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Install FrontEnd & BackEnd Dependencies
          command: |
            npm install
      - run:
          name: Build FrontEnd & BackEnd
          command: |
            npm run build
      - run:
          name: Deploy App
          command: |
            npm run deploy
