version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "server/package.json" }}
      - run:
          name: Install BackEnd Dependencies
          command: |
            npm run install:server
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "server/package.json" }}
          paths: 
            - server/node_modules  
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "client/package.json" }}
      - run:
          name: Install FrontEnd Dependencies
          command: |
            npm run install:client
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "client/package.json" }}
          paths: 
            - client/node_modules  
      - run:
          name: Lint FrontEnd Application
          command: |
            npm run lint:client
      - run:
          name: Lint Backend Application
          command: |
            npm run lint:server
      - run:
          name: Test FrontEnd Application
          command: |
            npm run test:client
      - run:
          name: Build BackEnd
          command: |
            npm run build:server
          filters:
            branches:
              only:
                - main
      - run:
          name: Build FrontEnd
          command: |
            npm run build:client
          filters:
            branches:
              only:
                - main
      - run:
          name: Deploy Backend App
          command: |
            npm run deploy:server
      - run:
          name: Deploy FrontEnd App
          command: |
            npm run deploy:client
workflows:
  Storefront:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - master
