version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run install:client
      - run:
          name: Back-End Install
          command: |
            npm run install:server
      - run:
          name: Front-End Build
          command: |
            npm run build:server
      - run:
          name: Back-End Build
          command: |
            npm run build:client
      - run:
          name: Deploy App
          command: |
            npm run deploy
